### ISSUE TITLE
Make it possible to redraw plot without rerunning simulation?

### ISSUE THREAD

**Issue by drghirlanda** [learningsimulator/learningsimulator#174]
Right now, making a change to a plot entails rerunning the simulation, which may be time consuming. It would be great to be able to change plotting instructions and replot without rerunning the simulation.

**Comment by markusrobertjonsson** [comment]
@drghirlanda This is the intention of the "Plot" button. However, it doesn't seem to work. This is a bug. See #141.

**Comment by markusrobertjonsson** [comment]
@drghirlanda The "Plot" button should now work as intended. Please check and let me know if there are any problems.
