### ISSUE TITLE
Enable multiple expressions in export commands

### ISSUE THREAD

**Issue by markusrobertjonsson** [learningsimulator/learningsimulator#178]
Consider allowing multiple expressions in export commands (in particular the use of wildcards) that is already possible in plotting commands.

Currently, when exporting using for example
`@vexport s->b filename.csv`
The columns in `filename.csv` are 
`x,  v(s->b) subject 0,  v(s->b) subject 1,  ...`

Allowing multiple expressions with for example
`@vexport s->b1, s->b2 filename.csv`
we should get  the columns
`x,  v(s->b1) subject 0,  v(s->b2) subject 0, v(s->b1) subject 1,  v(s->b2) subject 2`
or
`x,  v(s->b1) subject 0,  v(s->b1) subject 1, v(s->b2) subject 0,  v(s->b2) subject 2`

**Comment by markusrobertjonsson** [comment]
@drghirlanda Do you have any comments? Also, do you prefer looping over subjects first, then expressions, or vice versa (in the order of rht ecolumns in the output file)?

**Comment by drghirlanda** [comment]
Yes, this would be really useful! Allowing wildcards would be great because sometimes there are many variables. I right now have a script with 100 stimuli and 4 actions, so 400 s->b pairs... It would be great if one could do:
    @vexport *->* filename.csv
and get all of the values. I have no preference regarding column order.
