### ISSUE TITLE
Emacs integration

### ISSUE THREAD

**Issue by drghirlanda** [learningsimulator/learningsimulator#183]
I put together an Emacs package to edit Learning Simulator scripts and run the simulator from within Emacs:

[https://github.com/drghirlanda/lesim-mode](https://github.com/drghirlanda/lesim-mode)

I think the old Emacs file can be removed from the simulator repository (if it's still there) and a pointer somewhere in the documentation could be added, if that's OK. The package is submitted for inclusion in the MELPA repository, hopefully it will be accepted.

**Comment by markusrobertjonsson** [comment]
Addressed in 2b9250f47dcf94a2a04a178ebbc9512c17dcd1e1.
