### ISSUE TITLE
Org-mode integration

### ISSUE THREAD

**Issue by drghirlanda** [learningsimulator/learningsimulator#184]
I'd like to integrate the Learning Simulator with org-mode for Emacs. Org-mode is a system for literate programming and reproducible research. It would be great if it were possible to directly save figures to file instead of doing that from the GUI. This would make it possible to drive the Learning Simulator from org-mode files seamlessly. This would also help reproducibility as no human intervention would be needed to produce output.

**Comment by markusrobertjonsson** [comment]
@drghirlanda With this suggestion, will the possibility to directly save figures to file be available only when using Emacs as script editor? If so, wouldn't an alternative be to add some builtin script-syntax for saving figures (like `@export`)?

**Comment by drghirlanda** [comment]
@markusrobertjonsson No, I was thinking about a scripting language feature. For example, a `@save` keyword, `@fexport` keyword, or providing `filename=` or `filename:` after `@figure`. Not sure which one is the best to parse. It would have to be set for each figure one wants to save. But it should not have anything to do with Emacs, so one would be able to use it from any system that can execute an external command.

**Comment by markusrobertjonsson** [comment]
Made a separate issue https://github.com/learningsimulator/learningsimulator/issues/198 about the saving of figures to image files.
