### ISSUE TITLE
Tests for random_seed

### ISSUE THREAD

**Issue by drghirlanda** [learningsimulator/learningsimulator#199]
The second test in tests/test_random_seed.py checks that a specific sequence of random numbers is generated. Passing this test requires running it with the same random number generator that produced the values hard coded in the test code. This means that the test can fail if run with a python version different from the one used to generate the hard coded values. Maybe this is too stringent? It looks like the test suite fails for me just because of this.

Maybe it would be better for the test code to run the script that sets the seed twice, and compare values across runs. This would check that setting the seed works as expected within the simulator, even if the numbers may change across python versions. The latter does not ensure 100% reproducibility of simulations, but it can be fixed only by having our own random number generator.

**Comment by markusrobertjonsson** [comment]
You are right. Testing against a hard-coded list is too stringent. The test function `test_without_seed` almost does what you suggest. I will amend it to do that. Until then, ignore this error from the test suite.
