### ISSUE TITLE
Is test_nplot.py: test_p_vs_n1 guaranteed to succeed?

### ISSUE THREAD

**Issue by drghirlanda** [learningsimulator/learningsimulator#204]
I got an assertion failure when `sum_of_squares` on line 257 was 0.306... instead of the desired value of <0.3. Looking at the script, I see that reaching `STEP2` is unconditionally rewarded for the first 60 trials, but this does not guarantee 100% a given value of `sum_of_squares`. An unlucky subject may  fail to progress to `STEP2` enough times within the first 60 trials. One way to guarantee an outcome is to use the new random_seed feature to eliminate this randomness. Another way is to change the condition `count(nju_trial)<=60` to something like `count(STEP2)<=60` so that the subject is guaranteed to receive 60 rewards. The stop condition should be changed accordingly, in this case.

**Comment by markusrobertjonsson** [comment]
Good point. Using `count(STEP2)<=60` sounds like the right thing to do, to capture what the test is testing. Feel free to change that 😃 .
