### ISSUE TITLE
Bug in @phase inheritance

### ISSUE THREAD

**Issue by drghirlanda** [learningsimulator/learningsimulator#76]
The following script tries to use phase inheritance by replacing a phase line definition with a new one:
```
stimulus_elements = s0, s1
behaviors         = b1, b2
beta              = 1
n_subjects        = 1
alpha_v           = 0.1
alpha_w           = 0.1
mechanism         = ga

@phase phase1 stop: S0==100
S0 s0 | S1
S1 s1 | S0

@phase(phase1) phase2 stop: S0==100
S1 s0 | S0

@run phase1, phase2
```
However, it gives the following error message:
```
exceptions.ParseException: Error on line 14: Duplicate of phase line label 'S1'.
```

**Comment by markusrobertjonsson** [comment]
The syntax for phase inheritance is
``
@phase phase2(phase1) stop:S0==100
``
See https://learningsimulator.readthedocs.io/en/latest/phase.html#inheriting-a-phase.

@drghirlanda Please close the issue if this is satisfactory.
