### ISSUE TITLE
Add possibility to change parameter values between phases

### ISSUE THREAD

**Issue by markusrobertjonsson** [learningsimulator/learningsimulator#79]
Add possibility to change parameter values between phases, in particular `behaviors`. Note, however, that changing e.g., behaviors may require a re-definition of `alpha_v`, `start_v`, `beta`, (whose indexing depends on `behaviors`) etc.

**Comment by markusrobertjonsson** [comment]
@drghirlanda I came across this issue while addressing https://github.com/learningsimulator/learningsimulator/issues/186. I currently see no reason to ever having to re-define `stimulus_elements` or `behaviors`. If that's the case, we could even issue an error if any of these are defined more than once. What do you think? Currently it is not clear what it would mean to re-define any of these (i) between phases, or (ii) between the last phase and @run.

**Comment by drghirlanda** [comment]
Yes, I am not clear why this would be useful...

**Comment by markusrobertjonsson** [comment]
In #186 redefinitions of behaviors and stimulus_elements are prohibited.
