### ISSUE TITLE
Refactor run

### ISSUE THREAD

**Issue by markusrobertjonsson** [learningsimulator/learningsimulator#89]
Suggestions for making the @run syntax simpler and more flexible: 

1. Allow runlabel right after `@run` without using `runlabel:`. So, an alternative syntax for
```
@run phase1, phase2  runlabel:myRunlabel
```
is
```
@run myRunlabel phase1, phase2
```
2. Allow phase names on separate lines
```
@run myRunlabel
    phase1
    phase2
```
is the same as 
```
@run myRunlabel phase1, phase2
```
3. Specify stop condition in `@run` statement:
```
@run myRunlabel
    phase1(stop: stop_cond)
    phase2(stop: stop_cond)
```

It should also be possible to do
```
@run myRunlabel phase1(stop: myCond1), phase2(stop: myCond2)
@run myRunlabel 
    phase1(stop: myCond1), phase2(stop: myCond2)
    phase3, phase4(stop: myCond4)
```
(where `phase2` requires a stop condition in `@phase`), or (for backward compatibility)
```
@run training(stop: myCond1), test(stop: myCond2)    runlabel:myRunlabel 
```

Override stop condition in `@phase` with the one specified in `@run`.

**Comment by markusrobertjonsson** [comment]
The only parameter that it makes sense to change between phases is stimulus_elements.

**Comment by drghirlanda** [comment]
This looks great! Perhaps for consistency it should be possible to omit the comma that separate phases in the one-line format:
`@run myRunLabel phase1 phase2`
This works if phase names cannot contain spaces (which I think it's the way it is.)

**Comment by markusrobertjonsson** [comment]
> This looks great! Perhaps for consistency it should be possible to omit the comma that separate phases in the one-line format: `@run myRunLabel phase1 phase2` This works if phase names cannot contain spaces (which I think it's the way it is.)

One may omit the comma. Release notes for the new release coming soon.
